remote_theme: "mmistakes/minimal-mistakes"

name: &name "Clay Dowling"

author:
        name: *name
        bio: "Bearded conference junkie."
        location: "Dexter, MI"
        email: "clay@lazarusid.com"
        uri: "http://claydowling.com"


defaults:
        # _posts
        - scope:
                type: posts
          values:
                  layout: single
                  author_profile: true
                  share: true
                  related: true
