remote_theme: "mmistakes/minimal-mistakes"

locale: "en-US"
title: "Conference Notes"
title_separator: "-"
description: "Notes from a conference junkie"
name: &name "Clay Dowling"

author:
        name: *name
        bio: "Bearded conference junkie."
        avatar: "images/clay-with-kronos.jpg"
        location: "Dexter, MI"
        email: "clay@lazarusid.com"
        uri: "http://claydowling.com"


defaults:
        # _posts
        - scope:
                path: ""
                type: posts
          values:
                  layout: single
                  author_profile: true
                  read_time: true
                  share: true
                  related: true
        # _pages
        - scope:
                path: ""
                type: pages
          values:
                layout: single
                author_profile: true
